//! One-shot YOLO contract compiler.
//!
//! Reads the three ErgoScript sources that the SigmaChain genesis state
//! refers to (emission, treasury_accumulation, lp_accumulation), runs
//! each through sigma-rust's `compile_canonical` against the local
//! Scala node at `localhost:9053`, and prints the resulting ErgoTree
//! bytes as hex for transcription into `ergo-chain-spec`.
//!
//! `compile_canonical` falls back to the Scala node when the pure-Rust
//! compile path produces bytes that diverge — so every output here is
//! guaranteed byte-identical to what the Scala toolchain would
//! produce. Genesis bytes are immutable; using canonical mode at
//! genesis-construction time removes any risk of a Rust-compiler edge
//! case silently shipping a non-canonical contract.
//!
//! API key is read from the `API_KEY` env var (matching the project
//! convention in `01-emission-tests/SKILL-rust-test-harness.md`).
//! The key is NEVER echoed by this binary.

use std::process::ExitCode;

use blake2::digest::consts::U32;
use blake2::{Blake2b, Digest};
use ergoscript_compiler::compiler::compile_canonical;
use ergoscript_compiler::script_env::ScriptEnv;
use ergotree_ir::serialization::SigmaSerializable;

/// One contract to compile.
struct Target {
    /// Short name used in the printed output and in the
    /// `ergo-chain-spec` constant name.
    name: &'static str,
    /// Absolute path to the `.es` source file.
    source_path: &'static str,
}

const NODE_URL: &str = "http://localhost:9053";

/// Three contracts that pin the SigmaChain genesis state:
/// - `emission.es` guards the genesis emission box (177,412,882.5 YOLO)
/// - `treasury_accumulation.es` receives 10% per block — its script
///   hash lives in the emission box's R4 register
/// - `lp_accumulation.es` receives 5% per block — its script hash
///   lives in the emission box's R5 register
const TARGETS: &[Target] = &[
    Target {
        name: "emission",
        source_path: "/home/cq/working-files/yolo-chain/01-emission-tests/emission.es",
    },
    Target {
        name: "treasury_accumulation",
        source_path: "/home/cq/working-files/yolo-chain/02-treasury-tests/treasury_accumulation.es",
    },
    Target {
        name: "lp_accumulation",
        source_path: "/home/cq/working-files/yolo-chain/03-lp-fund-tests/lp_accumulation.es",
    },
];

fn main() -> ExitCode {
    let api_key = match std::env::var("API_KEY") {
        Ok(k) if !k.is_empty() => k,
        _ => {
            eprintln!(
                "error: API_KEY env var is unset or empty.\n\
                 sigmachain-genesis-tool needs it to authenticate against the local Scala\n\
                 Ergo node at {NODE_URL} for canonical-mode compilation."
            );
            return ExitCode::FAILURE;
        }
    };

    let mut printed: Vec<(String, String, Option<bool>)> = Vec::new();

    for t in TARGETS {
        let source = match std::fs::read_to_string(t.source_path) {
            Ok(s) => s,
            Err(e) => {
                eprintln!("error: could not read {} for {}: {e}", t.source_path, t.name);
                return ExitCode::FAILURE;
            }
        };

        eprintln!("compiling {}…", t.name);
        let result = match compile_canonical(&source, ScriptEnv::new(), NODE_URL, &api_key) {
            Ok(r) => r,
            Err(e) => {
                eprintln!("error: compile_canonical failed for {}: {e:?}", t.name);
                return ExitCode::FAILURE;
            }
        };

        let bytes = match result.tree.sigma_serialize_bytes() {
            Ok(b) => b,
            Err(e) => {
                eprintln!(
                    "error: ErgoTree serialization failed for {}: {e:?}",
                    t.name
                );
                return ExitCode::FAILURE;
            }
        };
        let hex = hex::encode(&bytes);
        printed.push((t.name.to_string(), hex, result.matched));
    }

    println!("// Auto-generated by sigmachain-genesis-tool — do not edit by hand.");
    println!("// To regenerate: cd 07-sigmachain-node/sigmachain-genesis-tool && cargo run --release");
    println!();
    for (name, hex, matched) in &printed {
        let provenance = match matched {
            Some(true) => "Rust compiler — byte-match with Scala node",
            Some(false) => "Scala node fallback — Rust compiler diverged, canonical bytes from node",
            None => "Scala node — Rust compiler did not run",
        };
        let upper = name.to_uppercase();
        println!("/// ErgoTree wire bytes for `{}.es` ({}).", name, provenance);
        println!("pub const {}_ERGO_TREE_HEX: &str =", upper);
        // Split into 76-char chunks so the source file stays readable.
        let chunked: Vec<String> = hex
            .as_bytes()
            .chunks(76)
            .map(|c| format!("    \"{}\"", std::str::from_utf8(c).unwrap()))
            .collect();
        println!("{}", chunked.join("\n"));
        println!(";");
        println!();
    }

    eprintln!();
    eprintln!("all targets compiled. Hex constants written to stdout.");
    for (name, _, matched) in &printed {
        let tag = match matched {
            Some(true) => "LOCAL MATCH",
            Some(false) => "USED NODE  ",
            None => "NODE ONLY  ",
        };
        eprintln!("  {tag}  {name}");
    }

    if let Err(e) = write_genesis_boxes_json(&printed) {
        eprintln!("error: writing genesis_boxes.json failed: {e}");
        return ExitCode::FAILURE;
    }

    ExitCode::SUCCESS
}

/// Total nanoYOLO locked in the genesis emission box: 176,525,325 YOLO
/// in nano units. Sourced from `01-emission-tests/emission_model.py`
/// `genesis_box_value()`; sum of 5 explicit halving epochs + 15 tail
/// epochs at MIN_REWARD = 1 YOLO.
const GENESIS_EMISSION_VALUE_NANO: u64 = 176_525_325_000_000_000;

/// Deterministic seed for the emission NFT token id. Any node that
/// wants to verify the genesis emission box's `tokens(0)._1` can
/// recompute this hash and bind it to consensus parity.
const EMISSION_NFT_SEED: &[u8] = b"SigmaChain testnet emission NFT v1";

/// Genesis path conventionally uses an all-zero "transaction id" since
/// no minting transaction exists before block 1.
const GENESIS_TX_ID_HEX: &str = "0000000000000000000000000000000000000000000000000000000000000000";

/// Where the generated JSON lands. Two consumers `include_str!` from
/// here at parallel relative paths (chain-spec from
/// `ergo-chain-spec/src/lib.rs`, node from `ergo-node/src/genesis.rs`).
const GENESIS_JSON_PATH: &str = "/home/cq/working-files/yolo-chain/07-sigmachain-node/sigmachain-node/test-vectors/sigmachain-testnet/genesis_boxes.json";

fn blake2b256(data: &[u8]) -> [u8; 32] {
    let mut h = Blake2b::<U32>::new();
    h.update(data);
    let out = h.finalize();
    let mut arr = [0u8; 32];
    arr.copy_from_slice(&out);
    arr
}

/// Encode 32-byte payload as a sigma `Coll[Byte]` constant in the
/// register hex format expected by `additionalRegisters` —
/// `0e20<32-byte hex>`. `0e` is the type tag for `Coll[Byte]`, `20`
/// is the VLQ length prefix (= 32).
fn encode_coll_byte_32(payload: &[u8; 32]) -> String {
    format!("0e20{}", hex::encode(payload))
}

fn write_genesis_boxes_json(
    compiled: &[(String, String, Option<bool>)],
) -> Result<(), Box<dyn std::error::Error>> {
    let find = |needle: &str| -> &str {
        compiled
            .iter()
            .find(|(n, _, _)| n == needle)
            .map(|(_, hex, _)| hex.as_str())
            .expect("compile target missing")
    };

    let emission_hex = find("emission");
    let treasury_hex = find("treasury_accumulation");
    let lp_hex = find("lp_accumulation");

    let treasury_bytes = hex::decode(treasury_hex)?;
    let lp_bytes = hex::decode(lp_hex)?;
    let treasury_hash = blake2b256(&treasury_bytes);
    let lp_hash = blake2b256(&lp_bytes);
    let emission_nft_id = blake2b256(EMISSION_NFT_SEED);

    let r4 = encode_coll_byte_32(&treasury_hash);
    let r5 = encode_coll_byte_32(&lp_hash);

    let box_json = serde_json::json!([
        {
            "value": GENESIS_EMISSION_VALUE_NANO,
            "ergoTree": emission_hex,
            "creationHeight": 0,
            "assets": [
                {
                    "tokenId": hex::encode(emission_nft_id),
                    "amount": 1
                }
            ],
            "additionalRegisters": {
                "R4": r4,
                "R5": r5,
            },
            "transactionId": GENESIS_TX_ID_HEX,
            "index": 0
        }
    ]);

    let serialized = serde_json::to_string_pretty(&box_json)?;
    let path = std::path::Path::new(GENESIS_JSON_PATH);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, format!("{serialized}\n"))?;

    eprintln!();
    eprintln!("genesis_boxes.json written to:");
    eprintln!("  {GENESIS_JSON_PATH}");
    eprintln!();
    eprintln!("derived 32-byte ids:");
    eprintln!("  emission NFT id     = {}", hex::encode(emission_nft_id));
    eprintln!("  treasury script hash = {}", hex::encode(treasury_hash));
    eprintln!("  lp script hash       = {}", hex::encode(lp_hash));
    Ok(())
}
