//! One-shot YOLO contract compiler.
//!
//! Reads the three ErgoScript sources that the SigmaChain genesis state
//! refers to (emission, treasury_accumulation, lp_accumulation), runs
//! each through sigma-rust's `compile_canonical` against the local
//! Scala node at `localhost:9053`, and prints the resulting ErgoTree
//! bytes as hex for transcription into `ergo-chain-spec`.
//!
//! `compile_canonical` falls back to the Scala node when the pure-Rust
//! compile path produces bytes that diverge — so every output here is
//! guaranteed byte-identical to what the Scala toolchain would
//! produce. Genesis bytes are immutable; using canonical mode at
//! genesis-construction time removes any risk of a Rust-compiler edge
//! case silently shipping a non-canonical contract.
//!
//! API key is read from the `API_KEY` env var (matching the project
//! convention in `01-emission-tests/SKILL-rust-test-harness.md`).
//! The key is NEVER echoed by this binary.

use std::process::ExitCode;

use ergoscript_compiler::compiler::compile_canonical;
use ergoscript_compiler::script_env::ScriptEnv;
use ergotree_ir::serialization::SigmaSerializable;

/// One contract to compile.
struct Target {
    /// Short name used in the printed output and in the
    /// `ergo-chain-spec` constant name.
    name: &'static str,
    /// Absolute path to the `.es` source file.
    source_path: &'static str,
}

const NODE_URL: &str = "http://localhost:9053";

/// Three contracts that pin the SigmaChain genesis state:
/// - `emission.es` guards the genesis emission box (177,412,882.5 YOLO)
/// - `treasury_accumulation.es` receives 10% per block — its script
///   hash lives in the emission box's R4 register
/// - `lp_accumulation.es` receives 5% per block — its script hash
///   lives in the emission box's R5 register
const TARGETS: &[Target] = &[
    Target {
        name: "emission",
        source_path: "/home/cq/working-files/yolo-chain/01-emission-tests/emission.es",
    },
    Target {
        name: "treasury_accumulation",
        source_path: "/home/cq/working-files/yolo-chain/02-treasury-tests/treasury_accumulation.es",
    },
    Target {
        name: "lp_accumulation",
        source_path: "/home/cq/working-files/yolo-chain/03-lp-fund-tests/lp_accumulation.es",
    },
];

fn main() -> ExitCode {
    let api_key = match std::env::var("API_KEY") {
        Ok(k) if !k.is_empty() => k,
        _ => {
            eprintln!(
                "error: API_KEY env var is unset or empty.\n\
                 sigmachain-genesis-tool needs it to authenticate against the local Scala\n\
                 Ergo node at {NODE_URL} for canonical-mode compilation."
            );
            return ExitCode::FAILURE;
        }
    };

    let mut printed: Vec<(String, String, Option<bool>)> = Vec::new();

    for t in TARGETS {
        let source = match std::fs::read_to_string(t.source_path) {
            Ok(s) => s,
            Err(e) => {
                eprintln!("error: could not read {} for {}: {e}", t.source_path, t.name);
                return ExitCode::FAILURE;
            }
        };

        eprintln!("compiling {}…", t.name);
        let result = match compile_canonical(&source, ScriptEnv::new(), NODE_URL, &api_key) {
            Ok(r) => r,
            Err(e) => {
                eprintln!("error: compile_canonical failed for {}: {e:?}", t.name);
                return ExitCode::FAILURE;
            }
        };

        let bytes = match result.tree.sigma_serialize_bytes() {
            Ok(b) => b,
            Err(e) => {
                eprintln!(
                    "error: ErgoTree serialization failed for {}: {e:?}",
                    t.name
                );
                return ExitCode::FAILURE;
            }
        };
        let hex = hex::encode(&bytes);
        printed.push((t.name.to_string(), hex, result.matched));
    }

    println!("// Auto-generated by sigmachain-genesis-tool — do not edit by hand.");
    println!("// To regenerate: cd 07-sigmachain-node/sigmachain-genesis-tool && cargo run --release");
    println!();
    for (name, hex, matched) in &printed {
        let provenance = match matched {
            Some(true) => "Rust compiler — byte-match with Scala node",
            Some(false) => "Scala node fallback — Rust compiler diverged, canonical bytes from node",
            None => "Scala node — Rust compiler did not run",
        };
        let upper = name.to_uppercase();
        println!("/// ErgoTree wire bytes for `{}.es` ({}).", name, provenance);
        println!("pub const {}_ERGO_TREE_HEX: &str =", upper);
        // Split into 76-char chunks so the source file stays readable.
        let chunked: Vec<String> = hex
            .as_bytes()
            .chunks(76)
            .map(|c| format!("    \"{}\"", std::str::from_utf8(c).unwrap()))
            .collect();
        println!("{}", chunked.join("\n"));
        println!(";");
        println!();
    }

    eprintln!();
    eprintln!("all targets compiled. Hex constants written to stdout.");
    for (name, _, matched) in &printed {
        let tag = match matched {
            Some(true) => "LOCAL MATCH",
            Some(false) => "USED NODE  ",
            None => "NODE ONLY  ",
        };
        eprintln!("  {tag}  {name}");
    }
    ExitCode::SUCCESS
}
