//! Genesis box loading for state initialization.

use ergo_chain_spec::Network;
use ergo_primitives::digest::{Digest32, ModifierId};
use ergo_primitives::reader::VlqReader;
use ergo_ser::ergo_box::{serialize_ergo_box, ErgoBox, ErgoBoxCandidate};
use ergo_ser::ergo_tree::read_ergo_tree;
use ergo_ser::register::{AdditionalRegisters, RegisterValue};
use ergo_ser::sigma_value::read_constant;
use ergo_ser::token::Token;

#[derive(serde::Deserialize)]
struct GenesisBoxJson {
    value: u64,
    #[serde(rename = "ergoTree")]
    ergo_tree: String,
    #[serde(rename = "creationHeight")]
    creation_height: u32,
    #[serde(default)]
    assets: Vec<GenesisAssetJson>,
    #[serde(rename = "additionalRegisters", default)]
    additional_registers: std::collections::HashMap<String, String>,
    #[serde(rename = "transactionId")]
    transaction_id: String,
    index: u16,
}

#[derive(serde::Deserialize)]
struct GenesisAssetJson {
    #[serde(rename = "tokenId")]
    token_id: String,
    amount: u64,
}

pub fn mainnet_genesis_boxes() -> Vec<([u8; 32], Vec<u8>)> {
    let json = include_str!("../../test-vectors/mainnet/genesis_boxes.json");
    parse_genesis_boxes(json)
}

pub fn testnet_genesis_boxes() -> Vec<([u8; 32], Vec<u8>)> {
    let json = include_str!("../../test-vectors/testnet/genesis_boxes.json");
    parse_genesis_boxes(json)
}

/// SigmaChain testnet genesis boxes. Returns a single emission box
/// guarded by `emission.es` containing 176,525,325 YOLO in nano units
/// plus the singleton emission NFT. R4 / R5 hold the blake2b256
/// hashes of the treasury and LP accumulation scripts so emission.es
/// can verify the coinbase tx routes the per-block split to the
/// right addresses.
///
/// Treasury and LP accumulation boxes are NOT created at genesis —
/// emission.es creates them fresh every block as OUTPUTS(1) and
/// OUTPUTS(2) of the coinbase emission tx.
///
/// The JSON is generated by `07-sigmachain-node/sigmachain-genesis-tool`;
/// regenerate by running that tool when emission.es,
/// treasury_accumulation.es, or lp_accumulation.es change.
pub fn sigmachain_testnet_genesis_boxes() -> Vec<([u8; 32], Vec<u8>)> {
    let json = include_str!("../../test-vectors/sigmachain-testnet/genesis_boxes.json");
    parse_genesis_boxes(json)
}

/// Network-aware genesis seeding. Sole entry point for runtime
/// initialization — keeps the `match Network` arm contained to one
/// place so callers stay network-agnostic.
pub fn genesis_boxes_for(network: Network) -> Vec<([u8; 32], Vec<u8>)> {
    match network {
        Network::Mainnet => mainnet_genesis_boxes(),
        Network::Testnet => testnet_genesis_boxes(),
        Network::SigmaChainTestnet => sigmachain_testnet_genesis_boxes(),
    }
}

fn parse_genesis_boxes(json: &str) -> Vec<([u8; 32], Vec<u8>)> {
    let boxes: Vec<GenesisBoxJson> =
        serde_json::from_str(json).expect("failed to parse genesis boxes JSON");
    boxes
        .iter()
        .map(|jb| {
            let ergo_box = parse_one_box(jb);
            let box_id = ergo_box.box_id().expect("genesis box_id");
            let serialized = serialize_ergo_box(&ergo_box).expect("genesis serialize");
            (*box_id.as_bytes(), serialized)
        })
        .collect()
}

fn parse_one_box(json: &GenesisBoxJson) -> ErgoBox {
    let tree_bytes = hex::decode(&json.ergo_tree).unwrap();
    let mut r = VlqReader::new(&tree_bytes);
    let ergo_tree = read_ergo_tree(&mut r).unwrap();
    let mut reg_vec: Vec<(usize, RegisterValue)> = Vec::new();
    for (key, val_hex) in &json.additional_registers {
        let reg_idx = match key.as_str() {
            "R4" => 0,
            "R5" => 1,
            "R6" => 2,
            "R7" => 3,
            "R8" => 4,
            "R9" => 5,
            _ => panic!("unknown register {key}"),
        };
        let val_bytes = hex::decode(val_hex).unwrap();
        let mut vr = VlqReader::new(&val_bytes);
        let (tpe, value) = read_constant(&mut vr).unwrap();
        reg_vec.push((reg_idx, RegisterValue { tpe, value }));
    }
    reg_vec.sort_by_key(|(idx, _)| *idx);
    let registers = AdditionalRegisters {
        registers: reg_vec.into_iter().map(|(_, rv)| rv).collect(),
    };
    let tokens: Vec<Token> = json
        .assets
        .iter()
        .map(|a| {
            let id_bytes: [u8; 32] = hex::decode(&a.token_id)
                .expect("genesis asset token_id hex")
                .try_into()
                .expect("genesis asset token_id must be 32 bytes");
            Token {
                token_id: Digest32::from_bytes(id_bytes),
                amount: a.amount,
            }
        })
        .collect();
    let candidate = ErgoBoxCandidate::new(
        json.value,
        ergo_tree,
        json.creation_height,
        tokens,
        registers,
    )
    .unwrap();
    let tx_id: [u8; 32] = hex::decode(&json.transaction_id)
        .unwrap()
        .try_into()
        .unwrap();
    ErgoBox {
        candidate,
        transaction_id: ModifierId::from_bytes(tx_id),
        index: json.index,
    }
}


#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sigmachain_testnet_genesis_returns_one_emission_box() {
        let boxes = sigmachain_testnet_genesis_boxes();
        assert_eq!(boxes.len(), 1, "genesis should hold exactly one box");
    }

    #[test]
    fn sigmachain_testnet_emission_box_has_correct_value_and_nft() {
        let json = include_str!("../../test-vectors/sigmachain-testnet/genesis_boxes.json");
        let parsed: Vec<GenesisBoxJson> = serde_json::from_str(json).expect("parse");
        assert_eq!(parsed.len(), 1);
        let b = &parsed[0];

        // 176,525,325 YOLO in nano units — the .5-fixed total supply.
        assert_eq!(b.value, 176_525_325_000_000_000);
        assert_eq!(b.creation_height, 0);

        // Singleton emission NFT in tokens[0].
        assert_eq!(b.assets.len(), 1);
        assert_eq!(b.assets[0].amount, 1);
        assert_eq!(b.assets[0].token_id.len(), 64, "32-byte hex token id");

        // R4 and R5 hold the 32-byte treasury and LP script hashes
        // (Coll[Byte] of length 32 → "0e20" prefix + 64 hex chars).
        assert!(b.additional_registers.get("R4").unwrap().starts_with("0e20"));
        assert!(b.additional_registers.get("R5").unwrap().starts_with("0e20"));
        assert_eq!(b.additional_registers.get("R4").unwrap().len(), 4 + 64);
        assert_eq!(b.additional_registers.get("R5").unwrap().len(), 4 + 64);
    }

    #[test]
    fn sigmachain_testnet_emission_box_parses_into_runtime_form() {
        // Round-trip through parse_one_box and confirm the resulting
        // ErgoBox has a valid box_id and serializes cleanly.
        let boxes = sigmachain_testnet_genesis_boxes();
        assert_eq!(boxes.len(), 1);
        let (box_id, serialized) = &boxes[0];
        assert_eq!(box_id.len(), 32);
        // 1 = box id starts non-zero (the all-zero box id would
        // indicate a parser bug producing a degenerate box).
        assert_ne!(box_id, &[0u8; 32]);
        assert!(!serialized.is_empty());
    }
}

