//! ErgoTree wire bytes for the three contracts that pin the SigmaChain
//! genesis state.
//!
//! These constants are the **canonical** ErgoTree bytes for the
//! corresponding `.es` sources under `01-emission-tests/`,
//! `02-treasury-tests/`, and `03-lp-fund-tests/` — generated by
//! `07-sigmachain-node/sigmachain-genesis-tool/` running
//! `ergoscript-compiler::compile_canonical` against the local Scala
//! node at `localhost:9053`. Canonical mode means: the pure-Rust
//! compile output is checked against the Scala node's output, and the
//! node's bytes are used when they differ. Every constant here is
//! byte-identical to what `/script/p2sAddress` + `/script/addressToTree`
//! on a v6.0.x Scala node would produce.
//!
//! These bytes are vendored — `ergo-chain-spec` does NOT depend on the
//! compiler crate, so the workspace builds offline. To regenerate
//! after a contract source change:
//!
//! ```text
//! cd 07-sigmachain-node/sigmachain-genesis-tool && cargo run --release
//! ```
//!
//! Then transcribe the printed constants into this file.

/// ErgoTree wire bytes for `01-emission-tests/emission.es`.
///
/// Provenance at generation time: Scala node fallback (Rust compiler
/// diverged on this contract — canonical-mode swapped to the node's
/// bytes, matching Scala exactly). 438 bytes after the .5-fix rev
/// of emission.es (removed the halvings == 5 / 1.5625 YOLO arm so
/// the genesis supply stays integral).
pub const EMISSION_ERGO_TREE_HEX: &str = concat!(
    "101e04b0cec00104000580d0dbc3f40204020580e8eda1ba0104040580f4f6905d04060580ba",
    "bbc82e04080580dd9da4170580a8d6b9070580a8d6b9070580a8d6b907040004020400040404",
    "00040004000502051405c801050a05c801051405c801050a05c801d80ed601c1a7d6029da373",
    "00d6039590720273017302959372027303730495937202730573069593720273077308959372",
    "027309730a730bd60495917203730c7203730dd605b2a5730e00d606c17205d607c27205d608",
    "e4c6a7040ed609b2a5730f00d60ac17209d60be4c6a7050ed60c8cb2db6308a773100001d60d",
    "db63087205d60eb2a5731100d1ed91a38cc7a701ecededed9272017204edededededed91b172",
    "0d7312938cb2720d73130001720c938cb2720d731400027315937207c2a79372069972017204",
    "ed93e4c67205040e720893e4c67205050e720b938cc7720501a3ed93720a9d9c720473167317",
    "93cbc272097208ed93c1720e9d9c72047318731993cbc2720e720bededed8f72017204ed9372",
    "069d9c7201731a731b93cb72077208ed93720a9d9c7201731c731d93cbc27209720bafa5d901",
    "0f63afdb6308720fd901114d0e948c721101720c",
);

/// ErgoTree wire bytes for `02-treasury-tests/treasury_accumulation.es`.
///
/// Provenance at generation time: pure Rust compiler — byte-match
/// with the Scala node.
pub const TREASURY_ACCUMULATION_ERGO_TREE_HEX: &str = concat!(
    "100204000e20ecce6bc576975c9c17246f316caa34917705fc09416a83326c7af666f599180a",
    "d802d601b2a5730000d602c27201d1eced937202c2a792c17201c1a793cb72027301",
);

/// ErgoTree wire bytes for `03-lp-fund-tests/lp_accumulation.es`.
///
/// Provenance at generation time: pure Rust compiler — byte-match
/// with the Scala node.
pub const LP_ACCUMULATION_ERGO_TREE_HEX: &str = concat!(
    "100204000e20f7e52722204eab03cf13bea0772e0e00ee48f4a6f81396514d9a3b692d61b1e4",
    "d802d601b2a5730000d602c27201d1eced937202c2a792c17201c1a793cb72027301",
);

/// Decoded bytes for [`EMISSION_ERGO_TREE_HEX`]. Panics at startup if
/// the const hex is malformed (which would be a build-time bug, not a
/// runtime condition).
pub fn emission_ergo_tree_bytes() -> Vec<u8> {
    hex::decode(EMISSION_ERGO_TREE_HEX).expect("EMISSION_ERGO_TREE_HEX is malformed")
}

/// Decoded bytes for [`TREASURY_ACCUMULATION_ERGO_TREE_HEX`].
pub fn treasury_accumulation_ergo_tree_bytes() -> Vec<u8> {
    hex::decode(TREASURY_ACCUMULATION_ERGO_TREE_HEX)
        .expect("TREASURY_ACCUMULATION_ERGO_TREE_HEX is malformed")
}

/// Decoded bytes for [`LP_ACCUMULATION_ERGO_TREE_HEX`].
pub fn lp_accumulation_ergo_tree_bytes() -> Vec<u8> {
    hex::decode(LP_ACCUMULATION_ERGO_TREE_HEX).expect("LP_ACCUMULATION_ERGO_TREE_HEX is malformed")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_three_constants_decode_to_valid_hex() {
        let _ = emission_ergo_tree_bytes();
        let _ = treasury_accumulation_ergo_tree_bytes();
        let _ = lp_accumulation_ergo_tree_bytes();
    }

    #[test]
    fn byte_sizes_match_canonical_compile_output() {
        // Pin against drift — if a future regenerate run produces a
        // different size, the contract source changed and Phase 4
        // genesis box construction needs to be reviewed.
        // emission.es is 438 B (post-.5-fix; the older 6-halving rev
        // was 454 B before the halvings == 5 / 1.5625 YOLO arm was
        // removed).
        assert_eq!(emission_ergo_tree_bytes().len(), 438);
        assert_eq!(treasury_accumulation_ergo_tree_bytes().len(), 72);
        assert_eq!(lp_accumulation_ergo_tree_bytes().len(), 72);
    }

    #[test]
    fn ergo_tree_header_byte_is_v0_constant_segregated() {
        // All three contracts compile with constant segregation
        // enabled (Scala default). The header byte is 0x10 = v0 +
        // hasSize=false + hasConstants=true.
        assert_eq!(emission_ergo_tree_bytes()[0], 0x10);
        assert_eq!(treasury_accumulation_ergo_tree_bytes()[0], 0x10);
        assert_eq!(lp_accumulation_ergo_tree_bytes()[0], 0x10);
    }

    #[test]
    fn treasury_and_lp_share_body_shape() {
        // emission.es constructs the treasury and LP accumulation
        // boxes with the same "preserve script + preserve value +
        // hash check" pattern, parameterized only by the 32-byte
        // hash constant. The trailing portion after the embedded
        // hash constant should therefore be identical between the
        // two contracts. Pin this so any future divergence is caught
        // — divergence would mean the two contracts grew different
        // logic and the emission.es split logic might need updating.
        let t = treasury_accumulation_ergo_tree_bytes();
        let l = lp_accumulation_ergo_tree_bytes();
        assert_eq!(t.len(), l.len());
        // The embedded hash is constant index 1: header (1B) +
        // n_constants (1B) + const[0] type tag (1B) + const[0] value
        // (1B SInt VLQ) + const[1] type+length prefix (2B) + 32-byte
        // hash. Trailing body starts at offset 1+1+1+1+2+32 = 38.
        assert_eq!(t[38..], l[38..]);
    }
}
